apiVersion: v2
name: observability-kube-prometheus
description: A Weaveworks Helm chart for the kube-prometheus Profile
type: application
version: 0.0.1
dependencies:
  - name: kube-prometheus
    version: "8.1.11"
    repository: "https://charts.bitnami.com/bitnami"
kubeVersion: ">=1.16.0-0"
home: https://github.com/weaveworks/profiles-catalog
sources:
  - https://charts.bitnami.com/bitnami

keywords:
- prometheus
- alertmanager
- operator
- monitoring


maintainers:
  - name: Weaveworks
    email: support@weave.works

annotations:
  "weave.works/profile": observability-kube-prometheus
  "weave.works/category": Observability
  "weave.works/operator": "true"
  "weave.works/links": |
    - name: Chart Sources
      url: https://charts.bitnami.com/bitnami
    - name: Upstream Project
      url: https://github.com/bitnami/containers/tree/main/bitnami/prometheus-operator
  "weave.works/profile-ci": |
    - "gke"
    - "kind"
    - "eks"