{{- if .Values.externalSecret.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: clusterissuer-static-secret
  namespace: cert-manager
spec:
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.secretManager.path }}
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStore.name }}
  target:
    creationPolicy: Owner
    name: {{ .Values.externalSecret.secretName }}
status:
  refreshTime: null
{{- end }}