{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: weaveworks-elasticsearch-credentials
  namespace: {{ template "elk-stack.namespace" . }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
    app: {{ template "elk-stack.name" . }}
    chart: {{ template "elk-stack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  {{- if .Values.auth.password }}
  password: {{ .Values.auth.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}