ingress-nginx:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        networking.gke.io/load-balancer-type: "Internal"
        service.beta.kubernetes.io/azure-load-balancer-internal: "true"
        service.beta.kubernetes.io/oci-load-balancer-internal: "true"
