metallb:
  prometheus:
    # Set the prometheus namespace if podMonitor is enabled
    namespace: ""
    podMonitor:
      enabled: false
    prometheusRule:
      enabled: false
  configInline:
    address-pools:
      - name: default
        protocol: layer2
        # replace the address with a subnet address range for your environment
        # by adding 200 to the control plane IP.
        # For example for demo2, LM30 would be:
        # control plane: 172.16.20.30/32
        # MetalLB address: 172.16.20.230/32
        addresses:
        - 172.16.20.251/32
