
policy-agent:
  image: magalixcorp/policy-agent
  failurePolicy: Ignore

  # If you don't want to use cert-manager, set useCertManager to false and provide your own certs
  useCertManager: true
  certificate: ""
  key: ""
  caCertificate: ""

  persistence:
    enabled: false
    # claimStorage: 1Gi
    # sinkDir: /tmp
    # storageClassName: standard

  config:
    accountId: ""
    clusterId: ""

    audit:
      # Disable audit functionality
      enabled: false

    admission:
      # Enable admission functionality
      enabled: true
      sinks:
        # Enable writing violations as K8s events
        k8sEventsSink:
          enabled: true
