apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: {{ include "flamingo.fullname" . }}
  namespace: {{ template "flamingo.namespace" . }}
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
  annotations:
    metadata.weave.works/flamingo-fsa-demo: "https://localhost:8080/applications/argocd/fsa-demo?view=tree"
    link.argocd.argoproj.io/external-link: "http://localhost:9001/kustomize/details?clusterName=Default&name=fsa-demo&namespace=flux-system"
spec:
  prune: true
  interval: 2m
  path: "./demo"
  targetNamespace: {{ template "flamingo.namespace" . }}
  patches: 
  - patch: |
      apiVersion: apps/v1
      kind: Kustomization
      metadata:
        name: ignored
      spec:
        sourceRef:
          kind: OCIRepository
          name: {{ include "flamingo.fullname" . }}
          namespace: {{ template "flamingo.namespace" . }}
    target:
      kind: Kustomization
  sourceRef:
    kind: OCIRepository
    name: {{ include "flamingo.fullname" . }}
  timeout: 3m