apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: {{ include "flamingo.fullname" . }}
  namespace: {{ template "flamingo.namespace" . }}
  labels:
    {{- include "flamingo.labels" . | nindent 4 }}
  annotations:
    metadata.weave.works/flamingo-default-app: "https://localhost:8080/applications/argocd/default-app?view=tree"
    metadata.weave.works/flamingo-fsa-installation: "https://localhost:8080/applications/argocd/fsa-installation?view=tree"
    link.argocd.argoproj.io/external-link: "{{ .Values.gitopsURL }}/oci/details?clusterName=default%2F{{ .Values.clusterName }}&name=fsa-demo&namespace={{ template "flamingo.namespace" . }}"    
spec:
  interval: 30s
  url: {{ .Values.ociURL }}
  ref:
    tag: v2.7
